### ISSUE TITLE
Add padding-bottom to nav element

### ISSUE THREAD

**Issue by kbirk** [Nijikokun/minami#24]
Without padding on the bottom of the `nav` element, the lower-left URL preview displayed by most browsers obfuscates the bottom element:

![](https://i.imgur.com/6pmvxCW.png)

This can be prevented by adding:

``` css
nav {
    ...
    padding-bottom: 20px;
}
```
